spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus_db
    username: root
    password: lyf1577655659
  main:
    banner-mode: off
mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-prefix: tbl_
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# ??mp???
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
