spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus_db
    username: root
    password: lyf1577655659
  main:
    banner-mode: off
mybatis-plus:
  global-config:
    banner: false


